/* APL-1.0 licensed work; see LICENSE.TXT. */
package com.guillermomolina.protos.execution;
import static org.junit.jupiter.api.Assertions.*; import com.guillermomolina.protos.runtime.*; import java.math.BigInteger; import java.nio.file.Path; import java.util.List; import org.junit.jupiter.api.Test;
class ProtosStandardPathProtocolTest {
 private static ProtosPrelude core()throws Exception{return new ProtosCoreBootstrap().bootstrap(Path.of("protos","lib","core"));}
 @Test void constructionPreservesPortableStructure()throws Exception{var p=core();var q=(ProtosPathValue)new ProtosSourceCompiler().compile("Path.relative().child(\"a/b\").parentComponent().child(\"c\")").call(p.newModuleActivation());assertFalse(q.rooted());assertEquals(List.of(new ProtosPathValue.Normal("a/b"),ProtosPathValue.Parent.INSTANCE,new ProtosPathValue.Normal("c")),q.components());var z=(ProtosPathValue)new ProtosSourceCompiler().compile("Path.rooted()").call(p.newModuleActivation());assertTrue(z.rooted());assertTrue(z.components().isEmpty());}
 @Test void invalidNamesDomainsAndReceiversSignalError()throws Exception{var p=core();for(String s:new String[]{"Path.relative().child(\"\")","Path.relative().child(\".\")","Path.relative().child(\"..\")","Path.relative().child(1)","Path.child(\"x\")","Path.parentComponent()"})assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile(s).call(p.newModuleActivation()),s);}
 @Test void d037EqualityHashAndIndividualIdentity()throws Exception{var p=core();var r=(ProtosArrayValue)new ProtosSourceCompiler().compile("p1: Path.relative().child(\"same\")\np2: Path.relative().child(\"same\")\nArray(p1 == p2, p1 === p2, p1 !== p2, p1.hash(), p2.hash())").call(p.newModuleActivation());assertSame(ProtosBooleanValue.TRUE,r.indexedAt(BigInteger.ZERO));assertSame(ProtosBooleanValue.FALSE,r.indexedAt(BigInteger.ONE));assertSame(ProtosBooleanValue.TRUE,r.indexedAt(BigInteger.TWO));assertEquals(((ProtosIntegerValue)r.indexedAt(BigInteger.valueOf(3))).value(),((ProtosIntegerValue)r.indexedAt(BigInteger.valueOf(4))).value());}
 @Test void d037IdentityMapKeepsEqualIndependentPathsDistinct()throws Exception{var p=core();var r=(ProtosArrayValue)new ProtosSourceCompiler().compile("p1: Path.rooted().child(\"x\")\np2: Path.rooted().child(\"x\")\nm: IdentityMap()\nm.atPut(p1,10)\nm.atPut(p2,20)\nArray(m.size(),m.at(p1),m.at(p2))").call(p.newModuleActivation());assertEquals(BigInteger.TWO,((ProtosIntegerValue)r.indexedAt(BigInteger.ZERO)).value());assertEquals(BigInteger.TEN,((ProtosIntegerValue)r.indexedAt(BigInteger.ONE)).value());assertEquals(BigInteger.valueOf(20),((ProtosIntegerValue)r.indexedAt(BigInteger.TWO)).value());}
 @Test void representedLookupAndParentComponentAreDistinct()throws Exception{var p=core();var v=(ProtosPathValue)new ProtosSourceCompiler().compile("Path.relative()").call(p.newModuleActivation());assertSame(p.pathPrototype(),ProtosValueLookup.lookup(v,"child",p).orElseThrow().home());var a=p.newModuleActivation();a.context().createLocalSlot("v",v);var withParent=(ProtosPathValue)new ProtosSourceCompiler().compile("v.parentComponent()").call(a);assertSame(p.pathPrototype(),ProtosValueLookup.lookup(withParent,"child",p).orElseThrow().home());assertEquals(List.of(ProtosPathValue.Parent.INSTANCE),withParent.components());}
 @Test void frozenPreludeBindingAndSemanticMembership()throws Exception{var p=core();assertTrue(p.bindings().isFrozen());assertSame(p.pathPrototype(),p.bindings().readLocalSlot("Path").orElseThrow());var fake=new ProtosObjectValue(p.pathPrototype());var a=p.newModuleActivation();a.context().createLocalSlot("fake",fake);assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("fake.child(\"x\")").call(a));}
 @Test void equalityDistinguishesRootednessKindsAndValues()throws Exception{var p=core();var r=(ProtosArrayValue)new ProtosSourceCompiler().compile("a: Path.relative().child(\"x\")\nArray(a == Path.rooted().child(\"x\"), a == Path.relative().child(\"y\"), a == Path.relative().parentComponent(), a == 1)").call(p.newModuleActivation());for(int i=0;i<4;i++)assertSame(ProtosBooleanValue.FALSE,r.indexedAt(BigInteger.valueOf(i)));}
}
