/* APL-1.0 licensed work; see LICENSE.TXT. */
package com.guillermomolina.protos.execution;
import static org.junit.jupiter.api.Assertions.*; import com.guillermomolina.protos.runtime.*; import java.math.BigInteger; import java.nio.file.Path; import org.junit.jupiter.api.Test;
class ProtosStandardMapProtocolTest {
 private static ProtosPrelude core() throws Exception{return new ProtosCoreBootstrap().bootstrap(Path.of("protos","lib","core"));}
 @Test void factoryLookupUpdateSizeAndIdentity() throws Exception{ProtosPrelude p=core();Object r=new ProtosSourceCompiler().compile("m: Map()\nm.atPut(1, 10)\nm.atPut(2, 20)\nm.atPut(1.0, 11)\nArray(m.at(1), m.containsKey(2), m.size, m === Map())").call(p.newModuleActivation());ProtosArrayValue x=(ProtosArrayValue)r;assertEquals(BigInteger.valueOf(11),((ProtosIntegerValue)x.indexedAt(BigInteger.ZERO)).value());assertSame(ProtosBooleanValue.TRUE,x.indexedAt(BigInteger.ONE));assertEquals(BigInteger.TWO,((ProtosIntegerValue)x.indexedAt(BigInteger.TWO)).value());assertSame(ProtosBooleanValue.FALSE,x.indexedAt(BigInteger.valueOf(3)));}
 @Test void missingAndWrongReceiverSignal() throws Exception{ProtosPrelude p=core();assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("Map().at(1)").call(p.newModuleActivation()));assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("Map.at(1)").call(p.newModuleActivation()));}
 @Test void removeReturnsOldValue() throws Exception{ProtosPrelude p=core();Object r=new ProtosSourceCompiler().compile("m: Map()\nm.atPut(\"a\", 1)\nm.atPut(\"b\", 2)\nold: m.remove(\"a\")\nm.atPut(\"a\", 3)\nArray(old, m.size, m.at(\"a\"))").call(p.newModuleActivation());ProtosArrayValue x=(ProtosArrayValue)r;assertEquals(BigInteger.ONE,((ProtosIntegerValue)x.indexedAt(BigInteger.ZERO)).value());assertEquals(BigInteger.TWO,((ProtosIntegerValue)x.indexedAt(BigInteger.ONE)).value());assertEquals(BigInteger.valueOf(3),((ProtosIntegerValue)x.indexedAt(BigInteger.TWO)).value());}
 @Test void closedAndFrozenBoundaries() throws Exception{ProtosPrelude p=core();ProtosActivation a=p.newModuleActivation();ProtosMapValue m=new ProtosMapValue(p.mapPrototype());a.context().createLocalSlot("m",m);new ProtosSourceCompiler().compile("m.atPut(1,1)").call(a);m.close();new ProtosSourceCompiler().compile("m.atPut(1,2)").call(a);assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("m.atPut(2,2)").call(a));assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("m.remove(1)").call(a));m.freeze();assertThrows(ProtosSignalException.class,()->new ProtosSourceCompiler().compile("m.atPut(1,3)").call(a));}
}
