/* APL-1.0 licensed work; see LICENSE.TXT. */
package com.guillermomolina.protos.execution;
import static org.junit.jupiter.api.Assertions.*;
import com.guillermomolina.protos.runtime.*;import java.math.BigInteger;import java.nio.file.Path;import java.util.*;import org.junit.jupiter.api.Test;
class ProtosStandardBufferedByteIoProtocolTest {
 private static ProtosPrelude core()throws Exception{return new ProtosCoreBootstrap().bootstrap(Path.of("protos","lib","core"));}
 private static ProtosIntegerValue i(long n){return new ProtosIntegerValue(BigInteger.valueOf(n));}
 private static ProtosBytesValue bytes(ProtosObjectValue p,int...v){var b=new ProtosBytesValue(p);for(int x:v)b.indexedAdd(i(x));return b;}
 private static Object call(ProtosObjectValue o,String m,List<?> a,ProtosActivation x){return ProtosInvocation.invokeMessage(o,m,a,x);}
 @Test void factoriesAreFrozenAndCreateFreshBorrowingWrappers()throws Exception{var p=core();var a=p.newModuleActivation();var br=(ProtosObjectValue)p.bindings().readLocalSlot("BufferedReader").orElseThrow();assertTrue(br.isFrozen());var s=source(a);var x=(ProtosObjectValue)call(br,"call",List.of(s),a);var y=(ProtosObjectValue)call(br,"call",List.of(s),a);assertNotSame(x,y);assertTrue(x.hasLocalSlot("read"));assertTrue(x.hasLocalSlot("close"));assertFalse(x.hasLocalSlot("write"));}
 @Test void readerReturnsBufferedPrefixBeforeReenteringSourceAndFreshBytes()throws Exception{var p=core();var a=p.newModuleActivation();var s=source(a);var br=(ProtosObjectValue)p.bindings().readLocalSlot("BufferedReader").orElseThrow();var r=(ProtosObjectValue)call(br,"call",List.of(s),a);var f1=(ProtosFutureValue)call(r,"read",List.of(i(2)),a);var f2=(ProtosFutureValue)call(r,"read",List.of(i(2)),a);assertEquals(List.of(1,2),ints((ProtosBytesValue)f1.resolvedValue().orElseThrow()));assertEquals(List.of(3,4),ints((ProtosBytesValue)f2.resolvedValue().orElseThrow()));assertEquals(1,((Counter)s.readLocalSlot("counter").orElseThrow()).reads);}
 @Test void writerBuffersUntilFlushAndFlushesNestedFlushableTarget()throws Exception{var p=core();var a=p.newModuleActivation();var t=target(a);var bw=(ProtosObjectValue)p.bindings().readLocalSlot("BufferedWriter").orElseThrow();var w=(ProtosObjectValue)call(bw,"call",List.of(t),a);var wf=(ProtosFutureValue)call(w,"write",List.of(bytes((ProtosObjectValue)t.readLocalSlot("bp").orElseThrow(),7,8)),a);assertSame(w,wf.resolvedValue().orElseThrow());var c=(Counter)t.readLocalSlot("counter").orElseThrow();assertEquals(0,c.writes);var ff=(ProtosFutureValue)call(w,"flush",List.of(),a);assertSame(w,ff.resolvedValue().orElseThrow());assertEquals(1,c.writes);assertEquals(1,c.flushes);}
 @Test void borrowingCloseDoesNotCloseTargetButOwningCloseDoes()throws Exception{var p=core();var a=p.newModuleActivation();var bw=(ProtosObjectValue)p.bindings().readLocalSlot("BufferedWriter").orElseThrow();var t1=target(a);var b=(ProtosObjectValue)call(bw,"call",List.of(t1),a);call(b,"close",List.of(),a);assertEquals(0,((Counter)t1.readLocalSlot("counter").orElseThrow()).closes);var t2=target(a);var o=(ProtosObjectValue)call(bw,"owning",List.of(t2),a);call(o,"write",List.of(bytes((ProtosObjectValue)t2.readLocalSlot("bp").orElseThrow(),9)),a);var cf=(ProtosFutureValue)call(o,"close",List.of(),a);assertSame(o,cf.resolvedValue().orElseThrow());var c=(Counter)t2.readLocalSlot("counter").orElseThrow();assertEquals(1,c.writes);assertEquals(1,c.flushes);assertEquals(1,c.closes);}
 @Test void invalidArgumentsUseFailedFutureAfterDispatch()throws Exception{var p=core();var a=p.newModuleActivation();var br=(ProtosObjectValue)p.bindings().readLocalSlot("BufferedReader").orElseThrow();var r=(ProtosObjectValue)call(br,"call",List.of(source(a)),a);var f=(ProtosFutureValue)call(r,"read",List.of(i(0)),a);assertEquals(ProtosFutureValue.State.FAILED,f.state());}
 private static final class Counter{int reads,writes,flushes,closes;}
 private static ProtosObjectValue source(ProtosActivation a){var s=new ProtosObjectValue(ProtosObjectValue.rootObject());var c=new Counter();s.createLocalSlot("counter",c);s.createLocalSlot("read",ProtosClosureValue.nativeClosure((x,args)->{c.reads++;var f=new ProtosFutureValue(x.prelude().orElseThrow().futurePrototype(),x.executionDomain());var b=new ProtosBytesValue(new ProtosObjectValue(ProtosObjectValue.rootObject()));for(int n:new int[]{1,2,3,4})b.indexedAdd(i(n));f.resolve(b,x);return f;}));s.createLocalSlot("close",ProtosClosureValue.nativeClosure((x,args)->{c.closes++;var f=new ProtosFutureValue(x.prelude().orElseThrow().futurePrototype(),x.executionDomain());f.resolve(s,x);return f;}));return s;}
 private static ProtosObjectValue target(ProtosActivation a){var t=new ProtosObjectValue(ProtosObjectValue.rootObject());var bp=new ProtosObjectValue(ProtosObjectValue.rootObject());ProtosStandardBytesProtocol.install(bp);var c=new Counter();t.createLocalSlot("bp",bp);t.createLocalSlot("counter",c);t.createLocalSlot("write",ProtosClosureValue.nativeClosure((x,args)->{c.writes++;var f=new ProtosFutureValue(x.prelude().orElseThrow().futurePrototype(),x.executionDomain());f.resolve(t,x);return f;}));t.createLocalSlot("flush",ProtosClosureValue.nativeClosure((x,args)->{c.flushes++;var f=new ProtosFutureValue(x.prelude().orElseThrow().futurePrototype(),x.executionDomain());f.resolve(t,x);return f;}));t.createLocalSlot("close",ProtosClosureValue.nativeClosure((x,args)->{c.closes++;var f=new ProtosFutureValue(x.prelude().orElseThrow().futurePrototype(),x.executionDomain());f.resolve(t,x);return f;}));return t;}
 private static List<Integer> ints(ProtosBytesValue b){var r=new ArrayList<Integer>();for(int j=0,n=b.indexedSize().intValueExact();j<n;j++)r.add(((ProtosIntegerValue)b.indexedAt(BigInteger.valueOf(j))).value().intValue());return r;}
}
