#!/usr/bin/env python3
# THE LICENSED WORK IS PROVIDED UNDER THE TERMS OF THE ADAPTIVE PUBLIC LICENSE
# ("LICENSE") AS FIRST COMPLETED BY: Guillermo Adrián Molina. ANY USE, PUBLIC
# DISPLAY, PUBLIC PERFORMANCE, REPRODUCTION OR DISTRIBUTION OF, OR PREPARATION OF
# DERIVATIVE WORKS BASED ON, THE LICENSED WORK CONSTITUTES RECIPIENT'S ACCEPTANCE
# OF THIS LICENSE AND ITS TERMS, WHETHER OR NOT SUCH RECIPIENT READS THE TERMS OF
# THE LICENSE. "LICENSED WORK" AND "RECIPIENT" ARE DEFINED IN THE LICENSE. A COPY
# OF THE LICENSE IS LOCATED IN THE TEXT FILE ENTITLED "LICENSE.TXT" ACCOMPANYING
# THE CONTENTS OF THIS FILE. IF A COPY OF THE LICENSE DOES NOT ACCOMPANY THIS
# FILE, A COPY OF THE LICENSE MAY ALSO BE OBTAINED AT THE FOLLOWING WEB SITE:
# https://github.com/guillermomolina/protos
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
# the specific language governing rights and limitations under the License.


"""TEST009-D static guard: generated cached-dispatch BCI PE constancy.

At oracle/graal@95ce1499c8c96ab7d5a6697c5b4bf42160f3b68b the Bytecode DSL
generates, for every cached interpreter tier, a dispatch method annotated
@ExplodeLoop(kind = LoopExplosionKind.MERGE_EXPLODE) whose loop asserts

    CompilerAsserts.partialEvaluationConstant(bci);

before reading each instruction. Every value of `bci` that reaches the next
dispatch iteration must therefore remain a partial-evaluation constant.

This guard reads the Java generated by `make compile` (never src/main/java)
for the Protos generated roots, locates each cached dispatch, inventories
every write to its `bci`, and classifies each one:

  START_STATE_DECODE          bci decoded from the dispatch startState; proven
                              only when every generated continueAt entry site
                              is itself classified (ENTRY_* below)
  SEQUENTIAL_CONSTANT_DELTA   bci += <int literal> / bci = bci + <int literal>
  BYTECODE_IMMEDIATE_TARGET   BYTES.getIntUnaligned(bc, bci + <lit> /* imm
                              branch_target */) on the compilation-final
                              bytecode array
  MERGE_EXPLODE_KEY           CompilerDirectives.mergeExplodeKey(bci)
  THROWING_HANDLER            bci = <helper>(...) where the long/int helper has
                              no return statement, so (by javac's definite
                              completion rule) it always completes by throwing
                              and the throw is handled by the exception path
  PROVEN_HANDLER_RETURN       bci = <helper>(..., bc, bci, ...) where every
                              return of the helper is itself one of the proven
                              shapes above (bound to the helper parameters that
                              receive the dispatch bc/bci), an int literal, or
                              the unmodified bci
  DISPATCH_EXIT               the write is immediately followed by `return`,
                              so the value never reaches the next dispatch
  EXCEPTION_HANDLER_TABLE     bci = (int) handleException(...): every bci the
                              generated handler search can produce is drawn
                              from compilation-final structure (handler table,
                              tag-node enter/return BCIs, the original bci) or
                              is the 0xFFFFFFFF exit sentinel. Its handler
                              search is a non-exploded loop, so the static
                              proof is structural only: PE folding is
                              DYNAMIC and is discharged by
                              tools/generated_bytecode_bci_compilation_check.py

Anything else is RISK (ordinary runtime parameter, instance field,
frame/runtime state) or UNKNOWN (unrecognized shape, unresolved or
ambiguous helper, reassigned helper bci parameter). RISK and UNKNOWN always
fail and are never baselineable.

Entry sites (callers of continueAt that feed startState) are classified:

  ENTRY_LITERAL_ZERO        root execute: continueAt(bytecode, 0, ...)
  ENTRY_ROOT_STATE_LOOP     root continueAt loop: re-entry only after
                            CompilerDirectives.transferToInterpreterAndInvalidate
  ENTRY_CONTINUATION_LOCATION continuation resume from the @CompilationFinal
                            BytecodeLocation (premise: BytecodeLocation keeps a
                            final bytecodeIndex, truffle-api 25.4.4.1.1)
  ENTRY_OSR_TARGET          executeOSR(target) (premise: the Truffle OSR root
                            keeps target as a final field, truffle-runtime
                            25.4.4.1.1)

The exact topology (entry sites and every classified transition) is compared
with a reviewed baseline: a new, missing, or duplicated topology fails.
"""

from __future__ import print_function

import argparse
import bisect
import json
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

BASELINE_SCHEMA = "protos-generated-bytecode-bci-pe-baseline-v1"
EXPECTED_ROOTS = ("ProtosBytecodeRootNodeGen", "ProtosSemanticBytecodeRootNodeGen")

BCI_ASSERTION = "CompilerAsserts.partialEvaluationConstant(bci)"
MERGE_EXPLODE = "@ExplodeLoop(kind = LoopExplosionKind.MERGE_EXPLODE)"
CACHED_CLASS = re.compile(r"^CachedBytecodeNode\w*$")
# Bytecode immediates whose value is itself a bytecode index (a branch target).
BYTECODE_INDEX_IMMEDIATES = ("branch_target",)

PROVEN = "PROVEN"
DYNAMIC = "DYNAMIC"
RISK = "RISK"
UNKNOWN = "UNKNOWN"

START_STATE_DECODE = "START_STATE_DECODE"
SEQUENTIAL_CONSTANT_DELTA = "SEQUENTIAL_CONSTANT_DELTA"
BYTECODE_IMMEDIATE_TARGET = "BYTECODE_IMMEDIATE_TARGET"
MERGE_EXPLODE_KEY = "MERGE_EXPLODE_KEY"
PROVEN_HANDLER_RETURN = "PROVEN_HANDLER_RETURN"
THROWING_HANDLER = "THROWING_HANDLER"
DISPATCH_EXIT = "DISPATCH_EXIT"
EXCEPTION_HANDLER_TABLE = "EXCEPTION_HANDLER_TABLE"
RUNTIME_PARAMETER = "RUNTIME_PARAMETER"
INSTANCE_FIELD = "INSTANCE_FIELD"
RUNTIME_STATE = "RUNTIME_STATE"
UNKNOWN_SHAPE = "UNKNOWN"

ENTRY_LITERAL_ZERO = "ENTRY_LITERAL_ZERO"
ENTRY_ROOT_STATE_LOOP = "ENTRY_ROOT_STATE_LOOP"
ENTRY_CONTINUATION_LOCATION = "ENTRY_CONTINUATION_LOCATION"
ENTRY_OSR_TARGET = "ENTRY_OSR_TARGET"

PROVEN_KINDS = (START_STATE_DECODE, SEQUENTIAL_CONSTANT_DELTA, BYTECODE_IMMEDIATE_TARGET, MERGE_EXPLODE_KEY,
                PROVEN_HANDLER_RETURN, THROWING_HANDLER, DISPATCH_EXIT, ENTRY_LITERAL_ZERO, ENTRY_ROOT_STATE_LOOP,
                ENTRY_CONTINUATION_LOCATION, ENTRY_OSR_TARGET)
DYNAMIC_KINDS = (EXCEPTION_HANDLER_TABLE,)
BASELINEABLE_KINDS = PROVEN_KINDS + DYNAMIC_KINDS
ALL_KINDS = BASELINEABLE_KINDS + (RUNTIME_PARAMETER, INSTANCE_FIELD, RUNTIME_STATE, UNKNOWN_SHAPE)

INT_LITERAL = r"(?:0[xX][0-9a-fA-F]+|\d+)[lL]?"
IDENT = r"[A-Za-z_$][\w$]*"


class GuardError(Exception):
    pass


# ----------------------------------------------------------------------------
# Lexical helpers over generated Java.
# ----------------------------------------------------------------------------

def mask(source: str) -> str:
    """Blank comments and string/char literals, preserving offsets and newlines."""
    out = list(source)
    i, n = 0, len(source)

    def blank(start, end):
        for k in range(start, end):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        c = source[i]
        if source.startswith("//", i):
            end = source.find("\n", i)
            end = n if end < 0 else end
            blank(i, end)
            i = end
        elif source.startswith("/*", i):
            end = source.find("*/", i + 2)
            end = n if end < 0 else end + 2
            blank(i, end)
            i = end
        elif source.startswith('"""', i):
            end = source.find('"""', i + 3)
            end = n if end < 0 else end + 3
            blank(i + 1, end - 1)
            i = end
        elif c in "\"'":
            k = i + 1
            while k < n and source[k] != c and source[k] != "\n":
                k += 2 if source[k] == "\\" else 1
            end = min(k + 1, n)
            blank(i + 1, end - 1)
            i = end
        else:
            i += 1
    return "".join(out)


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def match_close(text: str, open_index: int) -> int:
    """Index just past the bracket matching text[open_index] in masked text."""
    pairs = {"{": "}", "(": ")", "[": "]"}
    opener = text[open_index]
    closer = pairs[opener]
    depth = 0
    for k in range(open_index, len(text)):
        if text[k] == opener:
            depth += 1
        elif text[k] == closer:
            depth -= 1
            if depth == 0:
                return k + 1
    raise GuardError("unbalanced %r at offset %d" % (opener, open_index))


def split_top(text: str, separator: str = ",") -> List[str]:
    parts, depth, start = [], 0, 0
    for k, c in enumerate(text):
        if c in "([{<":
            depth += 1
        elif c in ")]}>":
            depth -= 1
        elif c == separator and depth == 0:
            parts.append(text[start:k])
            start = k + 1
    tail = text[start:]
    if tail.strip() or parts:
        parts.append(tail)
    return [part.strip() for part in parts]


def statement_end(masked: str, start: int) -> int:
    depth = 0
    for k in range(start, len(masked)):
        c = masked[k]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == ";" and depth == 0:
            return k
    raise GuardError("unterminated statement at offset %d" % start)


# ----------------------------------------------------------------------------
# Structural model of a generated root.
# ----------------------------------------------------------------------------

class Method(object):
    def __init__(self, klass, name, header, params, body_start, body_end, line):
        self.klass = klass
        self.name = name
        self.header = header
        self.params = params
        self.body_start = body_start
        self.body_end = body_end
        self.line = line

    def param_names(self) -> List[str]:
        return [param.split()[-1] for param in self.params]


class JavaClass(object):
    def __init__(self, name, header, body_start, body_end):
        self.name = name
        self.header = header
        self.body_start = body_start
        self.body_end = body_end
        self.methods = []  # type: List[Method]

    def methods_named(self, name) -> List[Method]:
        return [method for method in self.methods if method.name == name]


CLASS_HEADER = re.compile(r"\b(?:class|interface|enum|record)\s+(" + IDENT + r")\b[^{;()]*\{")
METHOD_HEADER = re.compile(r"(" + IDENT + r")\s*\(")
JAVA_KEYWORDS = {"if", "for", "while", "switch", "catch", "synchronized", "return", "new", "throw", "else",
                 "try", "do", "super", "this", "assert"}


class GeneratedRoot(object):
    def __init__(self, name: str, source: str, label: str):
        self.name = name
        self.label = label
        self.source = source
        self.masked = mask(source)
        self.newlines = [index for index, char in enumerate(source) if char == "\n"]
        self.classes = []  # type: List[JavaClass]
        self._index_classes()

    def line_of(self, offset: int) -> int:
        return bisect.bisect_left(self.newlines, offset) + 1

    def _index_classes(self):
        for match in CLASS_HEADER.finditer(self.masked):
            open_index = match.end() - 1
            klass = JavaClass(match.group(1), self.masked[max(0, match.start() - 200):match.start()],
                              open_index + 1, match_close(self.masked, open_index) - 1)
            self.classes.append(klass)
        for klass in self.classes:
            self._index_methods(klass)

    def _index_methods(self, klass: JavaClass):
        masked = self.masked
        depth, k = 0, klass.body_start
        member_start = klass.body_start
        while k < klass.body_end:
            c = masked[k]
            if c == "{":
                if depth == 0 and masked.count("(", member_start, k) > masked.count(")", member_start, k):
                    # Array initializer inside an annotation argument, not a member body.
                    k = match_close(masked, k)
                    continue
                if depth == 0:
                    head = masked[member_start:k]
                    method = self._method_from_head(klass, head, member_start, k)
                    if method is not None:
                        klass.methods.append(method)
                    end = match_close(masked, k)
                    k = end
                    member_start = k
                    continue
                depth += 1
            elif c in ";}" and depth == 0:
                member_start = k + 1
            k += 1

    def _method_from_head(self, klass, head, head_start, open_index) -> Optional[Method]:
        if re.search(r"\b(class|interface|enum|record)\b", head) or "=" in head.split("(")[0]:
            return None
        stripped = head.rstrip()
        match = None
        for candidate in METHOD_HEADER.finditer(stripped):
            if candidate.group(1) in JAVA_KEYWORDS or candidate.group(1).startswith("@"):
                continue
            try:
                close = match_close(stripped, candidate.end() - 1)
            except GuardError:
                continue
            rest = stripped[close:].strip()
            if rest == "" or rest.startswith("throws"):
                preceding = stripped[:candidate.start()]
                if preceding.rstrip().endswith("@") or re.search(r"@" + IDENT + r"\s*$", preceding):
                    continue
                match = (candidate, close)
        if match is None:
            return None
        candidate, close = match
        params = [param for param in split_top(stripped[candidate.end():close - 1]) if param]
        params = [re.sub(r"@" + IDENT + r"(\([^)]*\))?\s*", "", param).replace("final ", "").strip()
                  for param in params]
        original_head = self.source[head_start:open_index]
        return Method(klass, candidate.group(1), normalize(original_head), params, open_index + 1,
                      match_close(self.masked, open_index) - 1, self.line_of(head_start + candidate.start()))

    def class_named(self, name: str) -> Optional[JavaClass]:
        found = [klass for klass in self.classes if klass.name == name]
        if len(found) > 1:
            raise GuardError("%s: class %s declared %d times" % (self.label, name, len(found)))
        return found[0] if found else None

    def body(self, method: Method, masked=True) -> str:
        return (self.masked if masked else self.source)[method.body_start:method.body_end]


# ----------------------------------------------------------------------------
# Classification.
# ----------------------------------------------------------------------------

class Transition(object):
    def __init__(self, root, dispatch, site, statement, kind, status, detail, line):
        self.root = root
        self.dispatch = dispatch
        self.site = site
        self.statement = statement
        self.kind = kind
        self.status = status
        self.detail = detail
        self.line = line

    def key(self) -> str:
        return "%s|%s|%s|%s|%s|%s" % (self.root, self.dispatch, self.site, self.statement, self.kind, self.detail)


class Dispatch(object):
    def __init__(self, root, klass, method):
        self.root = root
        self.klass = klass
        self.method = method
        self.assertions = 0
        self.initializations = []  # type: List[Transition]
        self.transitions = []  # type: List[Transition]

    def name(self) -> str:
        return "%s.%s" % (self.klass.name, self.method.name)


class Value(object):
    def __init__(self, kind, status, detail):
        self.kind = kind
        self.status = status
        self.detail = detail


def _immediate_name(original: str) -> Optional[str]:
    match = re.search(r"/\*\s*imm\s+(\w+)\s*\*/", original)
    return match.group(1) if match else None


def classify_value(expression: str, original: str, constant: Tuple[str, ...], bytecodes: Tuple[str, ...],
                   params: List[str], locals_: Tuple[str, ...]) -> Value:
    """Classify a value assigned to (or returned as) a bci in a scope where the
    names in `constant` hold the PE-constant dispatch bci and `bytecodes` hold
    the compilation-final bytecode array."""
    expr = normalize(expression)
    const = "(?:" + "|".join(re.escape(name) for name in constant) + ")" if constant else "(?!x)x"
    code = "(?:" + "|".join(re.escape(name) for name in bytecodes) + ")" if bytecodes else "(?!x)x"
    if re.fullmatch(r"-?" + INT_LITERAL, expr):
        return Value("CONSTANT_LITERAL", PROVEN, expr)
    if re.fullmatch(r"(?:\((?:int|long)\)\s*)?" + const, expr):
        return Value("IDENTITY", PROVEN, "bci")
    match = re.fullmatch(const + r"\s*([+-])\s*(" + INT_LITERAL + r")", expr)
    if match:
        return Value(SEQUENTIAL_CONSTANT_DELTA, PROVEN, "bci%s%s" % (match.group(1), match.group(2)))
    match = re.fullmatch(r"BYTES\.getIntUnaligned\(\s*" + code + r"\s*,\s*" + const + r"\s*\+\s*(" + INT_LITERAL
                         + r")\s*\)", expr)
    if match:
        immediate = _immediate_name(original)
        if immediate in BYTECODE_INDEX_IMMEDIATES:
            return Value(BYTECODE_IMMEDIATE_TARGET, PROVEN, "imm %s@bci+%s" % (immediate, match.group(1)))
        return Value(UNKNOWN_SHAPE, UNKNOWN, "bytecode immediate %r is not a BYTECODE_INDEX immediate" % immediate)
    if re.fullmatch(r"CompilerDirectives\.mergeExplodeKey\(\s*" + const + r"\s*\)", expr):
        return Value(MERGE_EXPLODE_KEY, PROVEN, "mergeExplodeKey(bci)")
    if expr.startswith("BYTES."):
        return Value(UNKNOWN_SHAPE, UNKNOWN, "unproven bytecode read %s" % expr)
    if re.search(r"\b(frame|localFrame|FRAMES|ACCESS)\b\s*\.|\bframe_\b|\.get(Long|Int|Object|Value)\w*\(", expr):
        return Value(RUNTIME_STATE, RISK, "frame/runtime state: %s" % expr)
    if re.fullmatch(r"(?:\((?:int|long)\)\s*)?" + IDENT, expr):
        name = re.sub(r"^\((?:int|long)\)\s*", "", expr)
        if name in params:
            return Value(RUNTIME_PARAMETER, RISK, "ordinary runtime parameter %s" % name)
        if name in locals_:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "local value %s" % name)
        return Value(INSTANCE_FIELD, RISK, "instance field %s" % name)
    if re.fullmatch(r"(?:\((?:int|long)\)\s*)?this\.\w+(\.\w+)*", expr) or re.fullmatch(
            r"(?:\((?:int|long)\)\s*)?\w+(\.\w+)+", expr):
        return Value(INSTANCE_FIELD, RISK, "field/runtime object state %s" % expr)
    return Value(UNKNOWN_SHAPE, UNKNOWN, "unrecognized bci value %s" % expr)


WRITE = re.compile(r"(?<![\w$.])bci\s*(>>>=|<<=|>>=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|=(?!=)|\+\+|--)")
PREFIX_WRITE = re.compile(r"(\+\+|--)\s*bci(?![\w$])")
CALL = re.compile(r"(" + IDENT + r")\s*\(")


def _locals_of(body: str) -> Tuple[str, ...]:
    return tuple(sorted(set(re.findall(r"\b(?:int|long|short|byte|Object|var)\s+(" + IDENT + r")\s*[=;]", body))))


class Analyzer(object):
    def __init__(self, root: GeneratedRoot):
        self.root = root
        self.failures = []  # type: List[str]

    # -- site labels ---------------------------------------------------------

    def site_label(self, method: Method, offset: int) -> str:
        """Enclosing switch-case / catch path of the statement at offset."""
        masked = self.root.masked
        stack = []  # entries: [kind, label]
        pending = None
        k = method.body_start
        token = re.compile(r"\bswitch\b|\bcatch\s*\(|\bcase\b|\bdefault\s*:|[{}]")
        position = k
        while True:
            match = token.search(masked, position, offset)
            if match is None:
                break
            text = match.group(0)
            if text == "switch":
                pending = ["switch", None]
                position = match.end()
            elif text.startswith("catch"):
                close = match_close(masked, match.end() - 1)
                pending = ["catch", "catch(%s)" % normalize(masked[match.end():close - 1]).split(" ")[0]]
                position = close
            elif text == "{":
                stack.append(pending if pending is not None else ["block", None])
                pending = None
                position = match.end()
            elif text == "}":
                if stack:
                    stack.pop()
                position = match.end()
            elif text == "case":
                colon = masked.find(":", match.end(), method.body_end)
                arrow = masked.find("->", match.end(), method.body_end)
                end = colon if arrow < 0 or (0 <= colon < arrow) else arrow
                for frame in reversed(stack):
                    if frame[0] == "switch":
                        frame[1] = "case " + normalize(masked[match.end():end])
                        break
                position = end + 1
            else:
                for frame in reversed(stack):
                    if frame[0] == "switch":
                        frame[1] = "default"
                        break
                position = match.end()
        labels = [frame[1] for frame in stack if frame[0] in ("switch", "catch") and frame[1]]
        return " > ".join(labels) if labels else "entry"

    # -- dispatch discovery ----------------------------------------------------

    def cached_dispatches(self) -> List[Dispatch]:
        dispatches = []
        cached = [klass for klass in self.root.classes if CACHED_CLASS.match(klass.name)]
        if not cached:
            self.failures.append("CACHED_DISPATCH_MISSING %s: no CachedBytecodeNode* class" % self.root.name)
        for klass in cached:
            explode = [method for method in klass.methods if MERGE_EXPLODE in method.header]
            if not explode:
                self.failures.append("CACHED_DISPATCH_MISSING %s.%s: no %s method" % (
                    self.root.name, klass.name, MERGE_EXPLODE))
                continue
            if len(explode) > 1:
                self.failures.append("DUPLICATE_TOPOLOGY %s.%s: %d MERGE_EXPLODE dispatch methods" % (
                    self.root.name, klass.name, len(explode)))
            for method in explode:
                dispatch = Dispatch(self.root.name, klass, method)
                dispatch.assertions = self.root.body(method).count(BCI_ASSERTION)
                if dispatch.assertions == 0:
                    self.failures.append("BCI_ASSERTION_MISSING %s.%s: no %s in the cached dispatch" % (
                        self.root.name, dispatch.name(), BCI_ASSERTION))
                dispatches.append(dispatch)
        return dispatches

    # -- dispatch transitions --------------------------------------------------

    def analyze_dispatch(self, dispatch: Dispatch, entries_proven: bool):
        root, method = self.root, dispatch.method
        masked, source = root.masked, root.source
        body = root.body(method)
        locals_ = _locals_of(body)
        params = method.param_names()
        declarations = list(re.finditer(r"\b(?:int|long)\s+bci\s*=", body))
        if len(declarations) != 1:
            self.failures.append("UNKNOWN %s %s: expected exactly one bci declaration, found %d" % (
                root.name, dispatch.name(), len(declarations)))
        bytecodes = self._dispatch_bytecodes(dispatch, body)
        writes = []
        for match in declarations:
            writes.append((method.body_start + match.start(), method.body_start + match.end(), True, "="))
        for match in WRITE.finditer(body):
            start = method.body_start + match.start()
            if any(start >= begin and start < end for begin, end, _, _ in writes):
                continue
            writes.append((start, method.body_start + match.end(), False, match.group(1)))
        for match in PREFIX_WRITE.finditer(body):
            start = method.body_start + match.start()
            writes.append((start, method.body_start + match.end(), False, match.group(1)))
        for start, op_end, is_declaration, operator in sorted(writes):
            end = statement_end(masked, op_end)
            statement_masked = masked[start:end]
            statement = normalize(source[start:end] + ";")
            rhs_masked = masked[op_end:end]
            rhs_original = source[op_end:end]
            site = self.site_label(method, start)
            line = root.line_of(start)
            if is_declaration:
                value = self._classify_initialization(rhs_masked, params, entries_proven)
                dispatch.initializations.append(Transition(root.name, dispatch.name(), site, statement, value.kind,
                                                           value.status, value.detail, line))
                continue
            value = self._classify_write(dispatch, operator, rhs_masked, rhs_original, end, bytecodes, params,
                                         locals_)
            dispatch.transitions.append(Transition(root.name, dispatch.name(), site, statement, value.kind,
                                                   value.status, value.detail, line))

    def _dispatch_bytecodes(self, dispatch: Dispatch, body: str) -> Tuple[str, ...]:
        names = []
        for match in re.finditer(r"\bbyte\[\]\s+(" + IDENT + r")\s*=\s*([^;]+);", body):
            init = normalize(match.group(2))
            if init in ("ACCESS.uncheckedCast(this.bytecodes, byte[].class)", "this.bytecodes", "bytecodes"):
                names.append(match.group(1))
        if names and not self.bytecodes_field_is_compilation_final():
            self.failures.append("UNKNOWN %s: bytecodes field is not @CompilationFinal(dimensions = 1) final" %
                                 self.root.name)
            return ()
        return tuple(names)

    def bytecodes_field_is_compilation_final(self) -> bool:
        return re.search(r"@CompilationFinal\(dimensions\s*=\s*1\)\s+final\s+byte\[\]\s+bytecodes\s*;",
                         self.root.masked) is not None

    def _classify_initialization(self, rhs: str, params: List[str], entries_proven: bool) -> Value:
        expr = normalize(rhs)
        match = re.fullmatch(r"(?:\(int\)\s*(" + IDENT + r")|decodeBci\(\s*(" + IDENT + r")\s*\))", expr)
        if match and (match.group(1) or match.group(2)) == "startState" and "startState" in params:
            if entries_proven:
                return Value(START_STATE_DECODE, PROVEN, expr)
            return Value(UNKNOWN_SHAPE, UNKNOWN, "startState decode with unproven entry sites")
        return Value(UNKNOWN_SHAPE, UNKNOWN, "unrecognized bci initialization %s" % expr)

    def _next_statement(self, end: int) -> str:
        return self.root.masked[end + 1:end + 400].lstrip()

    def _classify_write(self, dispatch, operator, rhs_masked, rhs_original, end, bytecodes, params,
                        locals_) -> Value:
        expr = normalize(rhs_masked)
        if operator in ("+=", "-="):
            if re.fullmatch(INT_LITERAL, expr):
                return Value(SEQUENTIAL_CONSTANT_DELTA, PROVEN, "bci%s%s" % (operator[0], expr))
            return Value(UNKNOWN_SHAPE, UNKNOWN, "non-literal delta bci %s %s" % (operator, expr))
        if operator in ("++", "--"):
            return Value(SEQUENTIAL_CONSTANT_DELTA, PROVEN, "bci%s1" % operator[0])
        if operator != "=":
            return Value(UNKNOWN_SHAPE, UNKNOWN, "compound bci write %s %s" % (operator, expr))
        exits = self._next_statement(end).startswith("return ") or self._next_statement(end).startswith("return(")
        call = re.fullmatch(r"(" + IDENT + r")\s*\((.*)\)", expr)
        if call and call.group(1) not in ("BYTES", "CompilerDirectives") and "." not in call.group(1):
            helper = self.analyze_helper(dispatch, call.group(1), call.group(2))
            if exits:
                return Value(DISPATCH_EXIT, PROVEN, "%s -> return" % call.group(1))
            return helper
        state = re.fullmatch(r"\(int\)\s*(" + IDENT + r")", expr)
        if state and state.group(1) in locals_:
            return self.analyze_exception_state(dispatch, state.group(1), end)
        value = classify_value(rhs_masked, rhs_original, ("bci",), bytecodes, params, locals_)
        if exits and value.status != PROVEN:
            return Value(DISPATCH_EXIT, PROVEN, "%s -> return" % expr)
        return value

    # -- helpers ---------------------------------------------------------------

    def _bind(self, helper: Method, arguments: str):
        args = split_top(arguments)
        names = helper.param_names()
        if len(args) != len(names):
            return None
        constant = tuple(name for name, arg in zip(names, args) if arg == "bci")
        bytecodes = tuple(name for name, arg in zip(names, args) if arg == "bc")
        return constant, bytecodes

    def analyze_helper(self, dispatch: Dispatch, name: str, arguments: str) -> Value:
        candidates = dispatch.klass.methods_named(name)
        if len(candidates) != 1:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "%s helper %s resolves to %d methods" % (
                "ambiguous" if candidates else "unresolved", name, len(candidates)))
        helper = candidates[0]
        binding = self._bind(helper, arguments)
        if binding is None:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "helper %s arity mismatch" % name)
        constant, bytecodes = binding
        if bytecodes and not self.bytecodes_field_is_compilation_final():
            bytecodes = ()
        body = self.root.body(helper)
        for param in constant:
            if re.search(r"(?<![\w$.])" + re.escape(param) + r"\s*(?:[-+*/%&|^]|<<|>>>?)?=(?!=)|(?:\+\+|--)\s*"
                         + re.escape(param) + r"(?![\w$])|(?<![\w$.])" + re.escape(param) + r"\s*(?:\+\+|--)",
                         body):
                return Value(UNKNOWN_SHAPE, UNKNOWN, "helper %s reassigns its bci parameter %s" % (name, param))
        returns = list(re.finditer(r"\breturn\b\s*([^;]*);", body))
        lambdas = re.search(r"->|\bnew\s+" + IDENT + r"\s*\([^;]*\)\s*\{", body)
        if not returns:
            # javac rejects a value-returning method that can complete normally, so a
            # long/int helper without any return statement can only complete by throwing.
            if re.search(r"\b(?:long|int)\s+" + re.escape(name) + r"\s*\(", helper.header) and not lambdas:
                return Value(THROWING_HANDLER, PROVEN, "%s always throws" % name)
            return Value(UNKNOWN_SHAPE, UNKNOWN, "helper %s has no return" % name)
        if lambdas:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "helper %s contains a lambda or anonymous class" % name)
        params = helper.param_names()
        locals_ = _locals_of(body)
        shapes = []
        worst = None
        for match in returns:
            start = helper.body_start + match.start(1)
            end = helper.body_start + match.end(1)
            value = classify_value(self.root.masked[start:end], self.root.source[start:end], constant, bytecodes,
                                   params, locals_)
            if value.status != PROVEN:
                if worst is None or (worst.status == RISK and value.status == UNKNOWN):
                    worst = Value(value.kind, value.status, "helper %s returns %s" % (name, value.detail))
            shapes.append("%s:%s" % (value.kind, value.detail) if value.kind not in (
                SEQUENTIAL_CONSTANT_DELTA, BYTECODE_IMMEDIATE_TARGET, "IDENTITY", "CONSTANT_LITERAL",
                MERGE_EXPLODE_KEY) else value.detail)
        if worst is not None:
            return worst
        return Value(PROVEN_HANDLER_RETURN, PROVEN, "%s returns %s" % (name, "|".join(sorted(set(shapes)))))

    # -- exception path --------------------------------------------------------

    EXCEPTION_BCI_VALUES = (
        r"originalBci",
        r"node\.enterBci",
        r"node\.returnBci\s*\+\s*" + INT_LITERAL,
        r"handlerTable\[\s*handler\s*\+\s*EXCEPTION_HANDLER_OFFSET_HANDLER_BCI\s*\]",
    )
    EXCEPTION_RETURNS = (
        r"target",
        r"\(\(sp & 0xFFFFFFFFL\) << 32\) \| \(bci & 0xFFFFFFFFL\)",
    )

    def analyze_exception_state(self, dispatch: Dispatch, local: str, end: int) -> Value:
        body = self.root.body(dispatch.method)
        declaration = re.search(r"\blong\s+" + re.escape(local) + r"\s*=\s*(" + IDENT + r")\s*\(([^;]*)\)\s*;", body)
        if declaration is None:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "bci from local %s of unknown origin" % local)
        name = declaration.group(1)
        follow = normalize(self._next_statement(end)[:120])
        if not follow.startswith("if (bci == 0xFFFFFFFF) { return %s; }" % local):
            return Value(UNKNOWN_SHAPE, UNKNOWN, "exception state without the 0xFFFFFFFF exit check")
        candidates = dispatch.klass.methods_named(name)
        if len(candidates) != 1:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "exception helper %s resolves to %d methods" % (
                name, len(candidates)))
        helper = candidates[0]
        binding = self._bind(helper, declaration.group(2))
        if binding is None or binding[0] != ("originalBci",):
            return Value(UNKNOWN_SHAPE, UNKNOWN, "exception helper %s does not bind bci to originalBci" % name)
        problems = self._exception_helper_problems(dispatch, helper)
        if problems:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "exception helper %s: %s" % (name, "; ".join(problems)))
        return Value(EXCEPTION_HANDLER_TABLE, DYNAMIC,
                     "%s: originalBci|handler-table|tag enter/return bci|0xFFFFFFFF exit" % name)

    def _exception_helper_problems(self, dispatch: Dispatch, helper: Method) -> List[str]:
        problems = []
        masked = self.root.masked
        body = self.root.body(helper)
        if re.search(r"(?<![\w$.])originalBci\s*(?:[-+*/%&|^]|<<|>>>?)?=(?!=)", body):
            problems.append("originalBci reassigned")
        for match in WRITE.finditer(body):
            if match.group(1) != "=":
                problems.append("compound bci write %s" % match.group(1))
                continue
            stmt_end = statement_end(body, match.end())
            value = normalize(body[match.end():stmt_end])
            if not any(re.fullmatch(pattern, value) for pattern in self.EXCEPTION_BCI_VALUES):
                problems.append("unproven bci value %s" % value)
        declaration = re.search(r"\blong\s+bci\s*=\s*([^;]*);", body)
        if declaration is None or normalize(declaration.group(1)) != "originalBci":
            problems.append("local bci is not initialized from originalBci")
        for match in re.finditer(r"\breturn\b\s*([^;]*);", body):
            value = normalize(match.group(1))
            if not any(re.fullmatch(pattern, value) for pattern in self.EXCEPTION_RETURNS):
                problems.append("unproven return %s" % value)
        if re.search(r"\breturn\s+target\s*;", body):
            target = re.search(r"\blong\s+target\s*=\s*(" + IDENT + r")\s*\(", body)
            if target is None:
                problems.append("return target of unknown origin")
            else:
                problems.extend(self._sentinel_only_problems(dispatch, target.group(1)))
        if "handlerTable[" in body:
            if not re.search(r"\bint\[\]\s+handlerTable\s*=\s*this\.handlers\s*;", body):
                problems.append("handlerTable is not this.handlers")
            if not re.search(r"@CompilationFinal\(dimensions\s*=\s*1\)\s+final\s+int\[\]\s+handlers\s*;", masked):
                problems.append("handlers field is not @CompilationFinal(dimensions = 1) final")
            resolve = re.search(r"\bhandler\s*=\s*(" + IDENT + r")\s*\(\s*bci\s*,", body)
            if resolve is None:
                problems.append("handler index of unknown origin")
            else:
                resolvers = dispatch.klass.methods_named(resolve.group(1))
                if len(resolvers) != 1 or "@ExplodeLoop" not in resolvers[0].header:
                    problems.append("handler resolver %s is not a unique @ExplodeLoop method" % resolve.group(1))
            if re.search(r"\bhandler\s*=", re.sub(r"\bhandler\s*=\s*" + IDENT + r"\s*\(\s*bci\s*,", "", body)
                         .replace("int handler = -EXCEPTION_HANDLER_LENGTH;", "")):
                problems.append("handler index assigned from another source")
        if "node." in body:
            if not re.search(r"\bTagNode\s+node\s*=\s*this\.tagRoot\.tagNodes\[\s*handlerTable\[\s*handler\s*\+\s*"
                             r"EXCEPTION_HANDLER_OFFSET_HANDLER_BCI\s*\]\s*\]\s*;", body):
                problems.append("tag node of unknown origin")
            for pattern, what in (
                    (r"@Child\s+(?:private\s+)?TagRootNode\s+tagRoot\s*;", "tagRoot is not a @Child"),
                    (r"@CompilationFinal\(dimensions\s*=\s*1\)\s+final\s+TagNode\[\]\s+tagNodes\s*;",
                     "tagNodes is not @CompilationFinal(dimensions = 1) final"),
                    (r"\bfinal\s+int\s+enterBci\s*;", "enterBci is not final"),
                    (r"@CompilationFinal\s+int\s+returnBci\s*;", "returnBci is not @CompilationFinal")):
                if not re.search(pattern, masked):
                    problems.append(what)
        return problems

    def _sentinel_only_problems(self, dispatch: Dispatch, name: str) -> List[str]:
        candidates = dispatch.klass.methods_named(name)
        if len(candidates) != 1:
            return ["control-flow helper %s resolves to %d methods" % (name, len(candidates))]
        problems = []
        returns = re.findall(r"\breturn\b\s*([^;]*);", self.root.body(candidates[0]))
        if not returns:
            problems.append("control-flow helper %s has no return" % name)
        for value in returns:
            if not re.fullmatch(r"\(.*\) \| 0xFFFFFFFFL", normalize(value)):
                problems.append("control-flow helper %s returns non-sentinel %s" % (name, normalize(value)))
        return problems

    # -- entry sites -----------------------------------------------------------

    def entry_sites(self) -> List[Transition]:
        root = self.root
        masked = root.masked
        sites = []
        for match in re.finditer(r"(?<![\w$])continueAt\s*\(", masked):
            start = match.start()
            prefix = masked[max(0, start - 80):start]
            if re.search(r"\b(?:long|Object|void|int)\s*$", prefix):
                continue  # declaration
            method = self._enclosing_method(start)
            stmt_start = max(masked.rfind(";", 0, start), masked.rfind("{", 0, start), masked.rfind("}", 0, start)) + 1
            end = statement_end(masked, start)
            statement = normalize(masked[stmt_start:end] + ";")
            line = root.line_of(start)
            klass = method.klass.name if method else "?"
            where = "%s.%s" % (klass, method.name if method else "?")
            value = self._classify_entry(method, statement, end)
            sites.append(Transition(root.name, "<entry>", where, statement, value.kind, value.status, value.detail,
                                    line))
        return sites

    def _enclosing_method(self, offset: int) -> Optional[Method]:
        best = None
        for klass in self.root.classes:
            for method in klass.methods:
                if method.body_start <= offset < method.body_end:
                    if best is None or method.body_start > best.body_start:
                        best = method
        return best

    def _classify_entry(self, method: Optional[Method], statement: str, end: int) -> Value:
        if method is None:
            return Value(UNKNOWN_SHAPE, UNKNOWN, "continueAt call outside a method")
        masked = self.root.masked
        body = self.root.body(method)
        if method.name == "execute" and re.fullmatch(
                r"return continueAt\(\s*\w+\s*,\s*0\s*,[^;]*\);", statement) and method.klass.name in EXPECTED_ROOTS:
            return Value(ENTRY_LITERAL_ZERO, PROVEN, "bci=0")
        if method.name == "continueAt" and method.klass.name in EXPECTED_ROOTS and re.fullmatch(
                r"state = bc\.continueAt\(this, frame, state, continuationRootNode\);", statement):
            rest = normalize(masked[end + 1:method.body_end])
            ok = re.match(r"if \(\(int\) state == 0xFFFFFFFF\) \{ break; \} else \{ "
                          r"CompilerDirectives\.transferToInterpreterAndInvalidate\(\);", rest)
            initial = re.search(r"long state = \(\(sp & 0xFFFFFFFFL\) << 32\) \| \(bci & 0xFFFFFFFFL\);",
                                normalize(body))
            if ok and initial and "bci" in method.param_names():
                return Value(ENTRY_ROOT_STATE_LOOP, PROVEN,
                             "initial bci from root continueAt caller; re-entry after transferToInterpreterAndInvalidate")
            return Value(UNKNOWN_SHAPE, UNKNOWN, "root continueAt loop without deopt-only re-entry")
        if method.name == "execute" and method.klass.name == "ContinuationRootNodeImpl" and re.fullmatch(
                r"return root\.continueAt\(bytecodeNode, bytecodeLocation\.getBytecodeIndex\(\), sp, targetFrame, "
                r"this\);", statement):
            if re.search(r"\bBytecodeLocation\s+bytecodeLocation\s*=\s*location\s*;", body) and re.search(
                    r"@CompilationFinal\s+(?:volatile\s+)?BytecodeLocation\s+location\s*;",
                    masked[method.klass.body_start:method.klass.body_end]) and re.search(
                    r"\bfinal\s+int\s+sp\s*;", masked[method.klass.body_start:method.klass.body_end]):
                return Value(ENTRY_CONTINUATION_LOCATION, PROVEN, "@CompilationFinal BytecodeLocation.bytecodeIndex")
            return Value(UNKNOWN_SHAPE, UNKNOWN, "continuation resume location is not compilation-final")
        if method.name == "executeOSR" and re.fullmatch(
                r"return continueAt\(getRoot\(\), \(FrameWithoutBoxing\) frame, target, null\);", statement) and \
                method.param_names()[1:2] == ["target"]:
            return Value(ENTRY_OSR_TARGET, PROVEN, "Truffle OSR root final target")
        return Value(UNKNOWN_SHAPE, UNKNOWN, "unrecognized continueAt entry %s" % statement)

    # -- whole root ------------------------------------------------------------

    def analyze(self):
        entries = self.entry_sites()
        entries_proven = bool(entries) and all(entry.status == PROVEN for entry in entries)
        if not entries:
            self.failures.append("UNKNOWN %s: no continueAt entry sites found" % self.root.name)
        dispatches = self.cached_dispatches()
        for dispatch in dispatches:
            self.analyze_dispatch(dispatch, entries_proven)
        return entries, dispatches


# ----------------------------------------------------------------------------
# Discovery, baseline, report.
# ----------------------------------------------------------------------------

def discover(generated: Path) -> Tuple[Dict[str, Path], List[str]]:
    found, failures = OrderedDict(), []
    if not generated.is_dir():
        return found, ["GENERATED_SOURCES_MISSING %s is not a directory (run make compile)" % generated]
    for name in EXPECTED_ROOTS:
        paths = sorted(generated.rglob(name + ".java"))
        if not paths:
            failures.append("GENERATED_ROOT_MISSING %s.java under %s" % (name, generated))
        elif len(paths) > 1:
            failures.append("DUPLICATE_TOPOLOGY %s.java found %d times: %s" % (
                name, len(paths), ", ".join(str(path) for path in paths)))
        else:
            found[name] = paths[0]
    return found, failures


class Result(object):
    def __init__(self):
        self.roots = OrderedDict()  # name -> (entries, dispatches)
        self.failures = []  # type: List[str]

    def all_topology(self) -> List[Transition]:
        out = []
        for entries, dispatches in self.roots.values():
            out.extend(entries)
            for dispatch in dispatches:
                out.extend(dispatch.initializations)
                out.extend(dispatch.transitions)
        return out


def analyze_texts(texts: Dict[str, Tuple[str, str]], expected=EXPECTED_ROOTS) -> Result:
    """texts: root name -> (label, source)."""
    result = Result()
    for name in expected:
        if name not in texts:
            result.failures.append("GENERATED_ROOT_MISSING %s.java" % name)
            continue
        label, source = texts[name]
        try:
            analyzer = Analyzer(GeneratedRoot(name, source, label))
            entries, dispatches = analyzer.analyze()
        except GuardError as error:
            result.failures.append("ANALYSIS_FAILED %s: %s" % (name, error))
            continue
        result.failures.extend(analyzer.failures)
        result.roots[name] = (entries, dispatches)
    return result


def load_baseline(path: Path) -> List[str]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise GuardError("cannot read baseline %s: %s" % (path, error))
    if not isinstance(data, dict) or data.get("schema") != BASELINE_SCHEMA:
        raise GuardError("baseline %s: schema must be %s" % (path, BASELINE_SCHEMA))
    entries = data.get("topology")
    if not isinstance(entries, list) or not all(isinstance(entry, str) and entry for entry in entries):
        raise GuardError("baseline %s: 'topology' must be a list of non-empty strings" % path)
    for position, entry in enumerate(entries):
        fields = entry.split("|")
        if len(fields) < 6:
            raise GuardError("baseline entry %d is malformed: %r" % (position, entry))
        kinds = [field for field in fields[4:] if field in ALL_KINDS]
        if not kinds:
            raise GuardError("baseline entry %d has no known kind: %r" % (position, entry))
        if kinds[0] not in BASELINEABLE_KINDS:
            raise GuardError("baseline entry %d: kind %r is a risk/unknown and is never baselineable" % (
                position, kinds[0]))
    return entries


def verify(result: Result, baseline: List[str]) -> List[str]:
    failures = []
    computed = [transition.key() for transition in result.all_topology()]
    for key, count in sorted(Counter(computed).items()):
        if count > 1:
            failures.append("DUPLICATE_TOPOLOGY %s (x%d)" % (key, count))
    for key, count in sorted(Counter(baseline).items()):
        if count > 1:
            failures.append("DUPLICATE_TOPOLOGY baseline entry %s (x%d)" % (key, count))
    computed_set, baseline_set = set(computed), set(baseline)
    for transition in result.all_topology():
        if transition.status in (PROVEN, DYNAMIC) and transition.key() not in baseline_set:
            failures.append("NEW_TOPOLOGY %s:%d %s" % (transition.root, transition.line, transition.key()))
    for key in sorted(baseline_set - computed_set):
        failures.append("STALE_BASELINE %s" % key)
    return failures


def totals(result: Result) -> "OrderedDict[str, int]":
    out = OrderedDict()
    out["GENERATED_ROOTS_EXPECTED"] = len(EXPECTED_ROOTS)
    out["GENERATED_ROOTS_FOUND"] = len(result.roots)
    dispatches = [dispatch for _, items in result.roots.values() for dispatch in items]
    entries = [entry for items, _ in result.roots.values() for entry in items]
    transitions = [transition for dispatch in dispatches for transition in dispatch.transitions]
    initializations = [transition for dispatch in dispatches for transition in dispatch.initializations]
    everything = entries + initializations + transitions
    out["CACHED_DISPATCHES_FOUND"] = len(dispatches)
    out["DISPATCH_BCI_ASSERTIONS_FOUND"] = sum(dispatch.assertions for dispatch in dispatches)
    out["BCI_ENTRY_SITES"] = len(entries)
    out["BCI_INITIALIZATIONS"] = len(initializations)
    out["BCI_TRANSITIONS"] = len(transitions)
    out["BCI_TRANSITION_PROVEN"] = sum(1 for each in transitions if each.status == PROVEN)
    out["BCI_TRANSITION_DYNAMIC"] = sum(1 for each in transitions if each.status == DYNAMIC)
    out["BCI_TRANSITION_RISK"] = sum(1 for each in everything if each.status == RISK)
    out["BCI_TRANSITION_UNKNOWN"] = sum(1 for each in everything if each.status == UNKNOWN)
    return out


def report_json(result: Result, failures: List[str]) -> dict:
    roots = OrderedDict()
    for name, (entries, dispatches) in result.roots.items():
        roots[name] = OrderedDict([
            ("entries", [vars(entry) for entry in entries]),
            ("dispatches", [OrderedDict([
                ("dispatch", dispatch.name()),
                ("assertions", dispatch.assertions),
                ("initializations", [vars(each) for each in dispatch.initializations]),
                ("transitions", [vars(each) for each in dispatch.transitions]),
            ]) for dispatch in dispatches]),
        ])
    return OrderedDict([("totals", totals(result)), ("failures", failures), ("roots", roots)])


def candidate_baseline(result: Result) -> dict:
    return OrderedDict([
        ("schema", BASELINE_SCHEMA),
        ("description", "Exact generated cached-dispatch BCI topology proven safe (statically, or structurally plus "
                        "the dynamic compilation check for EXCEPTION_HANDLER_TABLE) at this Graal/Protos shape. "
                        "Risks and unknowns are never baselined."),
        ("topology", sorted(transition.key() for transition in result.all_topology()
                            if transition.status in (PROVEN, DYNAMIC))),
    ])


def check(generated: Path, baseline: Path, report: Optional[Path], candidate: Optional[Path],
          out=sys.stdout) -> int:
    paths, failures = discover(generated)
    texts = OrderedDict()
    for name, path in paths.items():
        texts[name] = (str(path), path.read_text(encoding="utf-8"))
    result = analyze_texts(texts)
    result.failures = failures + [failure for failure in result.failures
                                  if not (failure.startswith("GENERATED_ROOT_MISSING") and failures)]
    try:
        entries = load_baseline(baseline)
    except GuardError as error:
        print("generated-bytecode-bci-pe-guard: ANALYSIS_FAILED: %s" % error, file=out)
        return 1
    all_failures = list(result.failures)
    for transition in result.all_topology():
        if transition.status in (RISK, UNKNOWN):
            all_failures.append("%s %s:%d %s [%s] %s" % (
                transition.status, transition.root, transition.line, transition.site, transition.statement,
                transition.detail))
    all_failures.extend(verify(result, entries))
    print("generated-bytecode-bci-pe-guard: generated cached-dispatch BCI PE constancy", file=out)
    for name, (sites, dispatches) in result.roots.items():
        print("ROOT=%s" % name, file=out)
        kinds = Counter(entry.kind for entry in sites)
        print("  ENTRY_SITES=%d %s" % (len(sites), dict(sorted(kinds.items()))), file=out)
        for dispatch in dispatches:
            statuses = Counter(each.status for each in dispatch.transitions)
            print("  DISPATCH=%s" % dispatch.name(), file=out)
            print("    DISPATCH_BCI_ASSERTIONS=%d" % dispatch.assertions, file=out)
            print("    BCI_INITIALIZATIONS=%d %s" % (
                len(dispatch.initializations), sorted(each.kind for each in dispatch.initializations)), file=out)
            print("    BCI_TRANSITIONS=%d" % len(dispatch.transitions), file=out)
            for status in (PROVEN, DYNAMIC, RISK, UNKNOWN):
                print("    BCI_TRANSITION_%s=%d" % (status, statuses.get(status, 0)), file=out)
            for kind, count in sorted(Counter(each.kind for each in dispatch.transitions).items()):
                print("      %-28s %d" % (kind, count), file=out)
    for key, value in totals(result).items():
        print("%s=%d" % (key, value), file=out)
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps(report_json(result, all_failures), indent=2) + "\n", encoding="utf-8")
    if all_failures:
        print("generated-bytecode-bci-pe-guard: FAIL", file=out)
        for failure in all_failures:
            print("  " + failure, file=out)
        if candidate is not None and not any(each.status in (RISK, UNKNOWN) for each in result.all_topology()):
            candidate.parent.mkdir(parents=True, exist_ok=True)
            candidate.write_text(json.dumps(candidate_baseline(result), indent=2) + "\n", encoding="utf-8")
            print("Candidate topology baseline (proven sites only; review before adopting): %s" % candidate,
                  file=out)
        return 1
    print("generated-bytecode-bci-pe-guard: PASS", file=out)
    print("  topology baseline exact; EXCEPTION_HANDLER_TABLE transitions require the dynamic compilation check",
          file=out)
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command")
    check_parser = commands.add_parser("check")
    check_parser.add_argument("--generated", required=True, type=Path)
    check_parser.add_argument("--baseline", required=True, type=Path)
    check_parser.add_argument("--report", type=Path)
    check_parser.add_argument("--candidate", type=Path)
    args = parser.parse_args(argv)
    if args.command != "check":
        parser.print_help()
        return 2
    return check(args.generated, args.baseline, args.report, args.candidate)


if __name__ == "__main__":
    sys.exit(main())
